version: "3.7"
services:
  app:
    build:
      context: ./
      target: builder
    working_dir: /app
#    secrets:
#      - source: netrc
#        target: /root/.netrc
    networks:
      - default
    ports:
      - "8080:80"
    volumes:
      - .:/app
    command: tail -f /dev/null
    environment:
      - API_PORT=80
      - API_REQUEST_LOG=true
      - LOG_FORMAT=json
      - MONGODB_ADDRESSES=mongo:27017
      - MONGODB_DATABASE=domain
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_REPLICATE_SET=rs
      - MONGODB_ITEM_COLLECTION=items
  mongo:
    image: mongo:4.2
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGODB_ADDRESSES=mongo:27017
      - MONGODB_DATABASE=domain
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_REPLICATE_SET=rs
      - MONGODB_ITEM_COLLECTION=items
    entrypoint: ["scripts/mongo-setup.sh"]
          
#secrets:
#  netrc:
#    file: ~/.netrc