version: "3.7"
services:
  app:
    build:
      context: ./
      target: builder
    working_dir: /app
#    secrets:
#      - source: netrc
#        target: /root/.netrc
    networks:
      - default
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    command: tail -f /dev/null
    environment:
      - API_PORT=80
      - API_REQUEST_LOG=true
      - LOG_FORMAT=json

volumes:
  go-mod-cache:
#secrets:
#  netrc:
#    file: ~/.netrc