version: "3.7"
services:
  mongo:
    image: mongo:4.2
    ports: 
      - "27017"
    volumes:
      - ./scripts:/scripts
      - mongo:/data/db
    environment:
      - MONGODB_ADDRESSES=mongo:27017
      - MONGODB_DATABASE=domain
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_REPLICATE_SET=rs
    entrypoint: ["scripts/mongo-setup.sh"]

volumes:
  mongo: